name: planthor-identity-infrastructure

services:

  postgresql:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: planthor-admin
      POSTGRES_PASSWORD: Planthor@123
      POSTGRES_DB: PLANTHOR_IDENTITY
    volumes:
      - local-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: planthor-admin@planthor.com
      PGADMIN_DEFAULT_PASSWORD: Planthor@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local-pgdata:
  pgadmin-data:
